# Generated by Django 4.1 on 2022-08-30 04:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='tipo_solicitud',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('habilitado', models.CharField(choices=[('1', 'Habilitado'), ('0', 'Deshabilitado')], max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='tema_solicitud',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('habilitado', models.CharField(choices=[('1', 'Habilitado'), ('0', 'Deshabilitado')], max_length=1)),
                ('tipo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='datos.tipo_solicitud')),
            ],
        ),
        migrations.CreateModel(
            name='Subtema_solicitud',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('habilitado', models.CharField(choices=[('1', 'Habilitado'), ('0', 'Deshabilitado')], max_length=1)),
                ('tema', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='datos.tema_solicitud')),
            ],
        ),
    ]
