# Generated by Django 4.1 on 2022-09-09 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Atributos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre_atrib', models.CharField(max_length=255)),
                ('habilitado', models.CharField(choices=[('1', 'Habilitado'), ('0', 'Deshabilitado')], max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='pers_gen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Codigo_CN', models.CharField(max_length=255)),
                ('Nombre_CN', models.CharField(max_length=255)),
                ('MdC', models.CharField(max_length=255)),
                ('DRV', models.CharField(max_length=255)),
                ('Red', models.CharField(max_length=255)),
                ('CURP', models.CharField(max_length=255)),
                ('RFC', models.CharField(max_length=255)),
                ('Fecha_alta', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Roles_usr',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre_Rol', models.CharField(max_length=255)),
                ('habilitado', models.CharField(choices=[('1', 'Habilitado'), ('0', 'Deshabilitado')], max_length=1)),
            ],
        ),
    ]
