# Generated by Django 4.1 on 2022-09-10 01:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('datos', '0002_atributos_pers_gen_roles_usr'),
    ]

    operations = [
        migrations.CreateModel(
            name='users_sys',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('passw', models.CharField(max_length=255)),
                ('rol', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='datos.roles_usr')),
                ('usr', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='datos.pers_gen')),
            ],
        ),
    ]
