# Generated by Django 4.1 on 2022-10-04 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datos', '0003_users_sys'),
    ]

    operations = [
        migrations.AddField(
            model_name='pers_gen',
            name='email',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
