# Generated by Django 4.1 on 2022-10-17 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datos', '0004_pers_gen_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='pers_gen',
            name='Apellidos_CN',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
