# Generated by Django 4.1 on 2022-10-17 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datos', '0005_pers_gen_apellidos_cn'),
    ]

    operations = [
        migrations.CreateModel(
            name='entidades_rep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entidad', models.CharField(max_length=255)),
            ],
        ),
    ]
