# Generated by Django 4.1 on 2022-10-19 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datos', '0006_entidades_rep'),
    ]

    operations = [
        migrations.AddField(
            model_name='pers_gen',
            name='tel_cel',
            field=models.IntegerField(null=True),
        ),
    ]
