# Generated by Django 4.1 on 2022-11-05 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datos', '0008_alter_pers_gen_tel_cel'),
    ]

    operations = [
        migrations.CreateModel(
            name='primer_registro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CodigoCN_pers', models.CharField(max_length=255)),
                ('Nombre_pers', models.CharField(max_length=255)),
                ('ApellidoP_pers', models.CharField(max_length=255)),
                ('ApellidoM_pers', models.CharField(max_length=255)),
                ('CURP_pers', models.CharField(max_length=255)),
                ('CURPFile_pers', models.FileField(upload_to='Uploaded Files/')),
                ('INEFile_pers', models.FileField(upload_to='Uploaded Files/')),
            ],
        ),
    ]
