# Generated by Django 4.1 on 2022-11-05 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datos', '0009_primer_registro'),
    ]

    operations = [
        migrations.AddField(
            model_name='primer_registro',
            name='JSONresp_pers',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
