# Generated by Django 4.1 on 2022-11-26 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datos', '0011_alter_primer_registro_jsonresp_pers'),
    ]

    operations = [
        migrations.CreateModel(
            name='cj_usr',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usr_pers', models.CharField(max_length=255)),
                ('Nombre_usr', models.CharField(max_length=255)),
                ('fecha_alta_urs', models.CharField(max_length=255)),
                ('fecha_ultimo_ingreso', models.CharField(max_length=255)),
            ],
        ),
    ]
