# Generated by Django 4.1 on 2022-11-26 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datos', '0013_cj_usr_email_usr'),
    ]

    operations = [
        migrations.AddField(
            model_name='cj_usr',
            name='pass_usr',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
