# Generated by Django 4.1 on 2022-12-09 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datos', '0014_cj_usr_pass_usr'),
    ]

    operations = [
        migrations.CreateModel(
            name='usr_sol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CodigoCN_pers', models.CharField(max_length=255)),
                ('Tipo_sol', models.CharField(max_length=255)),
                ('Detalle_sol', models.CharField(max_length=255)),
                ('Fecha_sol', models.CharField(max_length=255)),
                ('Status_sol', models.CharField(max_length=255)),
                ('fecha_ult_mod', models.CharField(max_length=255)),
                ('usuario_mod_sol', models.CharField(max_length=255)),
                ('track', models.CharField(max_length=1000)),
                ('Doc1_sol', models.FileField(upload_to='Uploaded Files/tickets/')),
                ('Doc2_sol', models.FileField(upload_to='Uploaded Files/tickets/')),
            ],
        ),
        migrations.AddField(
            model_name='pers_gen',
            name='first_Acces',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
