# Generated by Django 4.1 on 2022-12-09 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datos', '0015_usr_sol_pers_gen_first_acces'),
    ]

    operations = [
        migrations.CreateModel(
            name='usr_sol_curp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CodigoCN_pers', models.CharField(max_length=255)),
                ('Tipo_sol', models.CharField(max_length=255)),
                ('Detalle_sol', models.CharField(max_length=255)),
                ('CURP_sol', models.CharField(max_length=255)),
                ('Fecha_sol', models.CharField(max_length=255)),
                ('Status_sol', models.CharField(max_length=255)),
                ('fecha_ult_mod', models.CharField(max_length=255)),
                ('usuario_mod_sol', models.CharField(max_length=255)),
                ('track', models.CharField(max_length=1000)),
                ('Doc1_sol', models.FileField(upload_to='Uploaded Files/tickets/')),
                ('Doc2_sol', models.FileField(upload_to='Uploaded Files/tickets/')),
            ],
        ),
        migrations.CreateModel(
            name='usr_sol_dom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CodigoCN_pers', models.CharField(max_length=255)),
                ('Tipo_sol', models.CharField(max_length=255)),
                ('Detalle_sol', models.CharField(max_length=255)),
                ('cp_sol', models.CharField(max_length=255)),
                ('estado_sol', models.CharField(max_length=255)),
                ('alc_mun_sol', models.CharField(max_length=255)),
                ('colonia_sol', models.CharField(max_length=255)),
                ('calle_sol', models.CharField(max_length=255)),
                ('NumInt_sol', models.CharField(max_length=255)),
                ('NumExt_sol', models.CharField(max_length=255)),
                ('Ref_sol', models.CharField(max_length=255)),
                ('Fecha_sol', models.CharField(max_length=255)),
                ('Status_sol', models.CharField(max_length=255)),
                ('fecha_ult_mod', models.CharField(max_length=255)),
                ('usuario_mod_sol', models.CharField(max_length=255)),
                ('track', models.CharField(max_length=1000)),
                ('Doc1_sol', models.FileField(upload_to='Uploaded Files/tickets/')),
            ],
        ),
        migrations.CreateModel(
            name='usr_sol_nom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CodigoCN_pers', models.CharField(max_length=255)),
                ('Tipo_sol', models.CharField(max_length=255)),
                ('Detalle_sol', models.CharField(max_length=255)),
                ('Nom_sol', models.CharField(max_length=255)),
                ('ApPat_sol', models.CharField(max_length=255)),
                ('ApMat_sol', models.CharField(max_length=255)),
                ('Fecha_sol', models.CharField(max_length=255)),
                ('Status_sol', models.CharField(max_length=255)),
                ('fecha_ult_mod', models.CharField(max_length=255)),
                ('usuario_mod_sol', models.CharField(max_length=255)),
                ('track', models.CharField(max_length=1000)),
                ('Doc1_sol', models.FileField(upload_to='Uploaded Files/tickets/')),
                ('Doc2_sol', models.FileField(upload_to='Uploaded Files/tickets/')),
            ],
        ),
        migrations.CreateModel(
            name='usr_sol_rfc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CodigoCN_pers', models.CharField(max_length=255)),
                ('Tipo_sol', models.CharField(max_length=255)),
                ('Detalle_sol', models.CharField(max_length=255)),
                ('RFC_sol', models.CharField(max_length=255)),
                ('Fecha_sol', models.CharField(max_length=255)),
                ('Status_sol', models.CharField(max_length=255)),
                ('fecha_ult_mod', models.CharField(max_length=255)),
                ('usuario_mod_sol', models.CharField(max_length=255)),
                ('track', models.CharField(max_length=1000)),
                ('Doc1_sol', models.FileField(upload_to='Uploaded Files/tickets/')),
                ('Doc2_sol', models.FileField(upload_to='Uploaded Files/tickets/')),
            ],
        ),
        migrations.DeleteModel(
            name='usr_sol',
        ),
    ]
